
project_id = "ryomveanixzshfatalcd"

[functions.fetch-ai-news]
verify_jwt = true

[functions.analyze-client]
verify_jwt = true

[functions.generate-linkedin-article]
verify_jwt = true

[functions.generate-newsletter]
verify_jwt = true

[functions.search-intel]
verify_jwt = true
