
# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"

# Configure redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set environment variables
[build.environment]
  NODE_VERSION = "18"

# Enable functions if needed
[functions]
  directory = "netlify/functions"

# Set proper MIME types for all assets
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Also add for source maps
[[headers]]
  for = "/*.map"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
