# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"

# Configure redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set environment variables
[build.environment]
  NODE_VERSION = "18"

# Enable functions if needed
[functions]
  directory = "netlify/functions"
