export type ClientBaseFields = {
  annual_revenue: number | null;
  background: string | null;
  company_size: string | null;
  contact_email: string | null;
  contact_name: string | null;
  contact_phone: string | null;
  created_at: string;
  industry: string | null;
  likelihood: number | null;
  name: string;
  notes: string | null;
  status: string | null;
  type: string;
  website: string | null;
  project_revenue: number | null;
  next_due_date: string | null;
  additional_contacts: any | null;
  urgent: boolean | null;
  project_revenue_signed_off: boolean | null;
  project_revenue_forecast: boolean | null;
  annual_revenue_signed_off: number | null;
  annual_revenue_forecast: number | null;
  forecast_jan: number | null;
  forecast_feb: number | null;
  forecast_mar: number | null;
  forecast_apr: number | null;
  forecast_may: number | null;
  forecast_jun: number | null;
  forecast_jul: number | null;
  forecast_aug: number | null;
  forecast_sep: number | null;
  forecast_oct: number | null;
  forecast_nov: number | null;
  forecast_dec: number | null;
  actual_jan: number | null;
  actual_feb: number | null;
  actual_mar: number | null;
  actual_apr: number | null;
  actual_may: number | null;
  actual_jun: number | null;
  actual_jul: number | null;
  actual_aug: number | null;
  actual_sep: number | null;
  actual_oct: number | null;
  actual_nov: number | null;
  actual_dec: number | null;
}